services:
  postgres:
    build:
      context: docker
      dockerfile: postgres/postgres.dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data-nocache
    volumes:
      - ./docker/postgres/db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
volumes:
  postgres_data:
